### ISSUE TITLE
Switch from gulp to rollup

### ISSUE THREAD

**Issue by edmorley** [metricsgraphics/metrics-graphics#902]
Rollup is a more modern build tool that many libraries have now switched to:
https://rollupjs.org/guide/en

Switching will likely improve the dividends from the ES6 work (#811), given its support for tree shaking etc.

**Comment by wlach** [comment]
I've started working on this in a PR (actually using rollup via gulp): #907. It's been a *ton* of work, but it's becoming increasingly obvious to me that the library is unmaintainable in its current form -- we really just need to start using proper modules and namespacing like it's 2016. 

I'm actually kind of feeling that maybe neutrino is a better fit for this library longer term (which I guess would imply using webpack rather than rollup) -- feels like it would be easier to configure, plus its presets for linting and tests would be handy. What do you think @edmorley?

**Comment by edmorley** [comment]
> I'm actually kind of feeling that maybe neutrino is a better fit for this library longer term (which I guess would imply using webpack rather than rollup) -- feels like it would be easier to configure, plus its presets for linting and tests would be handy. What do you think @edmorley?

Sorry the delayed reply. Personally I suspect rollup is a better option for libraries rather than webpack. The Neutrino library preset is also not very actively maintained. Setting up linting and tests is probably easier than one would expect when not using custom tools like Neutrino, since it becomes possible to just follow the standard guides (whereas when using eg Neutrino, one is "off the beaten path"). eg:
https://rollupjs.org/guide/en#babel
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#usage
https://jestjs.io/docs/en/getting-started (no need to bundle to run tests)

**Comment by edmorley** [comment]
This appears to now be fixed :-)
